spring:
  application:
    name: dubbo-auto-configure-consumer-demo
---
### mail邮件配置
spring:
  mail:
    host: smtp.qq.com
    username: gongsir0630@qq.com
    password: ufdkyrhsbasmdeca
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            reauired: true
---
### redis配置：redis服务器：172.16.250.46
spring:
  redis:
    host: 172.16.250.46
    port: 6379
    password: admin1234
    jedis:
      pool:
        max-idle: 8
        min-idle: 0
        max-active: 8
        max-wait: -1
    timeout: 3000
---
dubbo:
  config-center:
    address: zookeeper://172.16.250.42:2181
    ### 关闭配置中心启动检查
    check: false
  consumer:
    timeout: 3000
  ### 关闭所有服务的启动时检查 (没有提供者时报错)
    check: false
  ### 消费方应用名，用于计算依赖关系，不是匹配条件，不要与提供方一样
  application:
    name: consumer-app
---
server:
  port: 8080
---
image:
  location: /www/server/dubbo-test/images/
---
jwt:
  secret: LssILoveYou
  expiration: 3600