spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://127.0.0.1:3306/dubboConsumer
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    ### druid配置
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      filters: stat,wall,slf4j
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      use-global-data-source-stat: true
      web-stat-filter:
        enabled: true
        url-pattern: "/*"
        exclusions: "*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*"
      stat-view-servlet:
        url-pattern: "/druid/*"
        allow: 127.0.0.1
        deny: 192.168.1.73
        reset-enable: false
        login-username: root
        login-password: admin1234
---
### jpa配置
spring:
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    show-sql: true
---
spring:
  application:
    name: dubbo-auto-configure-consumer-demo
---
### mail邮件配置
spring:
  mail:
    host: smtp.qq.com
    username: gongsir0630@qq.com
    password: ufdkyrhsbasmdeca
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            reauired: true
---
### redis配置：redis服务器：172.16.250.46
spring:
  redis:
    host: 172.16.250.46
    port: 6379
    password: admin1234
    jedis:
      pool:
        max-idle: 8
        min-idle: 0
        max-active: 8
        max-wait: -1
    timeout: 3000
---
dubbo:
  config-center:
    address: zookeeper://172.16.250.42:2181
    ### 关闭配置中心启动检查
    check: false
  consumer:
    timeout: 3000
  ### 关闭所有服务的启动时检查 (没有提供者时报错)
    check: false
  ### 消费方应用名，用于计算依赖关系，不是匹配条件，不要与提供方一样
  application:
    name: consumer-app
  protocol:
    serialization: kryo
---
server:
  port: 8080
---
image:
  location: /www/server/dubbo-test/images/
---
jwt:
  secret: LssILoveYou
  expiration: 3600