spring:
  application:
    name: dubbo-auto-configure-consumer-sample
---
dubbo:
  config-center:
    address: zookeeper://172.16.250.42:2181
---
server:
  port: 8080
---
image:
  location: /www/server/dubbo-test/images/
---
jwt:
  secret: LssILoveYou
  expiration: 3600